name: Intergrate

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  Intergrate_Node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - run: npm run build --if-present
      - run: npm run test:staging
